version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
  # Note: errcheck is intentionally disabled. This codebase has many
  # intentionally-ignored errors (Close(), Write() on response writers, etc.)
  # that would require extensive exclusion rules. The static analyzers above
  # catch the most critical issues without false positives.
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"  # Disable quickfix suggestions (style preferences, not bugs)
        - "-ST*"  # Disable style checks (comment formatting, etc.)
