run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
  disable:
    - unused  # Disable unused checker (interfaces kept for documentation)

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (net.Conn).Close
      - (*github.com/ebfe/scard.Context).Release
      - (*github.com/ebfe/scard.Card).Disconnect
      - (*net/http.ResponseWriter).Write
      - (encoding/json.Encoder).Encode
      - (*github.com/gorilla/websocket.Conn).SetReadDeadline
      - (*github.com/gorilla/websocket.Conn).SetWriteDeadline
      - (*github.com/gorilla/websocket.Conn).WriteMessage

issues:
  exclude-rules:
    # Exclude test files from errcheck
    - path: _test\.go
      linters:
        - errcheck
    # Exclude debug commands entirely
    - path: cmd/debug-reader.*
      linters:
        - errcheck
    # Exclude service files (best-effort cleanup)
    - path: internal/service/
      linters:
        - errcheck
